Fixed Centible undo bug crash
appteamcarolina/AppTeamToolBox pull request #1
Opened 2023-02-07 20:35 UTC by erayala15

Changed fixIndexIfNeeded to return currIndex as nil instead of -1. Modified insert method so it doesn't break when given an empty array. Verified that unwrapping currIndex is safe in all instances.

2023-02-07 21:28 UTC, mnabokow requested changes

2023-02-07 21:28 UTC, mnabokow commented on Sources/AppTeamToolBox/MNQueueIterator.swift
> +        currIndex! = -1
This should be setting to `nil`, right?

2023-02-07 21:34 UTC, turner-white commented on Sources/AppTeamToolBox/MNQueueIterator.swift
> +        currIndex! = -1
Good catch. Thanks!

2023-02-13 08:23 UTC, mnabokow commented
Done, merging so we can push build to TestFlight.

2023-02-13 08:23 UTC, merged